var searchData=
[
  ['datos_20de_20usuarios_0',['Base de Datos de Usuarios',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md15',1,'']]],
  ['de_20acceso_20con_20freertos_20y_20display_20ssd1306_1',['Sistema de Control de Acceso con FreeRTOS y Display SSD1306',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html',1,'']]],
  ['de_20acceso_20con_20raspberry_20pi_20pico_2',['Sistema de Control de Acceso con Raspberry Pi Pico',['../index.html',1,'']]],
  ['de_20autenticación_20normal_3',['Proceso de Autenticación Normal',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md23',1,'']]],
  ['de_20compilación_4',['Comandos de Compilación',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md20',1,'']]],
  ['de_20contraseña_5',['de Contraseña',['../index.html#password_change',1,'Cambio de Contraseña'],['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md24',1,'Cambio de Contraseña']]],
  ['de_20control_20de_20acceso_20con_20freertos_20y_20display_20ssd1306_6',['Sistema de Control de Acceso con FreeRTOS y Display SSD1306',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html',1,'']]],
  ['de_20control_20de_20acceso_20con_20raspberry_20pi_20pico_7',['Sistema de Control de Acceso con Raspberry Pi Pico',['../index.html',1,'']]],
  ['de_20datos_20de_20usuarios_8',['Base de Datos de Usuarios',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md15',1,'']]],
  ['de_20errores_9',['de Errores',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md29',1,'Manejo de Errores'],['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md31',1,'Señalización de Errores']]],
  ['de_20freertos_10',['de FreeRTOS',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md26',1,'Características Técnicas de FreeRTOS'],['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md30',1,'Hooks de FreeRTOS'],['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md9',1,'Tareas de FreeRTOS']]],
  ['de_20hardware_11',['de Hardware',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md4',1,'Conexiones de Hardware'],['../index.html#hardware_sec',1,'Configuración de Hardware']]],
  ['de_20leds_12',['de LEDs',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md14',1,'Patrones de LEDs'],['../index.html#leds_hw',1,'Sistema de LEDs']]],
  ['de_20prueba_13',['Usuarios de Prueba',['../index.html#testing_sec',1,'']]],
  ['de_20señalización_14',['LEDs de Señalización',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md6',1,'']]],
  ['de_20seguridad_15',['de Seguridad',['../index.html#security_sec',1,'Características de Seguridad'],['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md17',1,'Funcionalidades de Seguridad']]],
  ['de_20software_16',['de Software',['../index.html#software_sec',1,'Arquitectura de Software'],['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md19',1,'Requisitos de Software']]],
  ['de_20uso_17',['Modo de Uso',['../index.html#usage_sec',1,'']]],
  ['de_20usuarios_18',['Base de Datos de Usuarios',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md15',1,'']]],
  ['del_20display_20ssd1306_19',['Funcionalidad del Display SSD1306',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md11',1,'']]],
  ['del_20kernel_20',['Configuración del Kernel',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md27',1,'']]],
  ['del_20proyecto_21',['Descripción del Proyecto',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md1',1,'']]],
  ['del_20sistema_22',['del Sistema',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md8',1,'Arquitectura del Sistema'],['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md2',1,'Características del Sistema'],['../index.html#states_sec',1,'Estados del Sistema'],['../index.html#modules_sec',1,'Módulos del Sistema'],['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md12',1,'Mensajes del Sistema'],['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md22',1,'Uso del Sistema']]],
  ['descripción_20del_20proyecto_23',['Descripción del Proyecto',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md1',1,'']]],
  ['despliegue_24',['Compilación y Despliegue',['../index.html#compilation_sec',1,'']]],
  ['detalles_20técnicos_25',['Detalles Técnicos',['../index.html#technical_sec',1,'']]],
  ['display_20ssd1306_26',['Display SSD1306',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md11',1,'Funcionalidad del Display SSD1306'],['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html',1,'Sistema de Control de Acceso con FreeRTOS y Display SSD1306']]],
  ['display_20ssd1306_20i2c_27',['Display SSD1306 I2C',['../md__r_e_a_d_m_e___p_r_o_y_e_c_t_o2.html#autotoc_md7',1,'']]]
];
